name: Create Redirect URL for the raw ontology file

on:
  push:
    tags:
      - '*'   # triggers on any tag push
  workflow_dispatch:

permissions:
  contents: write   # allow committing back to the repo

jobs:
  create-folder-and-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folder and index.html for tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "Creating folder and index.html for tag: $TAG_NAME"
          mkdir -p "docs/$TAG_NAME"
          cat << EOF > "docs/$TAG_NAME/index.html"
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; URL=https://raw.githubusercontent.com/AIdentifyAGE/aidentifyage-ontology/$TAG_NAME/AIdentifyAGE.owl" />
            </head>
            <body></body>
          </html>
          EOF

      - name: Commit and push folder + file
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/$TAG_NAME
          git commit -m "Add index.html for tag $TAG_NAME"
          git push origin HEAD:$TAG_NAME
